name: "SonarQube Scan Workflow"

on:
  push:
    branches:
      - main
      - staging

jobs:
  SonarQubeScan:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: SonarQube Scan
        uses: SonarSource/sonarqube-scan-action@v5.2.0
        with:
          args: >
            -Dsonar.organization=athallabf
            -Dsonar.projectKey=athallabf_rakitcode-devops
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
